---
# tasks file for webserver

- name: httpdconfigration
  package:
       name: "{{ package_name }}"
       state: present
- name: install git
  package:
          name: "git"
          state: present
- name: start httpd
  service:
          name: "{{ package_name }}"
          state: started
          enabled: yes
- name: copy github code
  copy:
          content: "hello from {{ ansible_hostname }}"
          dest: "{{ website }}"


