---
# tasks file for ec2
- name: launching AWS instance using Ansible
  ec2:
    key_name: "bobby_demo"
    instance_type: "{{ aws_instance_type }}"
    image: "{{ ami_id }}"
    wait: yes
    count: 3
    instance_tags:
      Name: "{{ aws_instance_tags }}"
    vpc_subnet_id: "{{ subnet_id }}"
    assign_public_ip: yes
    region: "{{ aws_region }}"
    state: present
    group_id: "{{  security_group_id  }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
   

- name: launching AWS instance for loadbalancer using Ansible
  ec2:
    key_name: "bobby_demo"
    instance_type: "{{ aws_instance_type }}"
    image: "{{ ami_id }}"
    wait: yes
    count: 1
    instance_tags:
      Name: "loadbalancer"
    vpc_subnet_id: "{{ subnet_id }}"
    assign_public_ip: yes
    region: "{{ aws_region }}"
    state: present
    group_id: "{{  security_group_id  }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"

